import appConstants from "../constants/app-constants";
import { ISongDetails, GenreEnum, DificulltyLevelEnum } from "./app-interfaces";
;

export const GridItemData: ISongDetails[] = [
  {
    id: 1,
    name: "Allegro in A Major",
    artist: "W.F.Bach",
    parts: 1,
    pages: 4,
    duration: "02:36",
    genre: GenreEnum.Classical,
    instrument: "piano",
    price: 17.99,
    songKey: "D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 2,
    name: "Aria in D Minor",
    artist: "A.Scarlatti",
    parts: 2,
    pages: 4,
    duration: "01:36",
    genre: GenreEnum.Classical,
    instrument: "piano",
    price: 20.99,
    songKey: "B Minor",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 3,
    name: "Sonata",
    artist: "L.V.Beethoven",
    parts: 2,
    pages: 6,
    duration: "05:26",
    genre: GenreEnum.Classical,
    instrument: "piano",
    price: 14.99,
    songKey: "A Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 4,
    name: "Nuvole Bianche",
    artist: "L.Einaudi",
    parts: 1,
    pages: 2,
    duration: "02:46",
    genre: GenreEnum.Classical,
    instrument: "piano",
    price: 13.99,
    songKey: "G Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 5,
    name: "Hallelujah",
    artist: "L.Cohen",
    parts: 1,
    pages: 3,
    duration: "02:46",
    genre: GenreEnum.Rock,
    instrument: "piano/guitar",
    price: 35.99,
    songKey: "D Minor",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 6,
    name: "Your Song",
    artist: "E.John",
    parts: 1,
    pages: 3,
    duration: "05:46",
    genre: GenreEnum.Rock,
    instrument: "piano/guitar",
    price: 14.99,
    songKey: "D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 7,
    name: "Valerie",
    artist: "A.Winehouse",
    parts: 1,
    pages: 4,
    duration: "03:45",
    genre: GenreEnum.Rock,
    instrument: "piano/guitar",
    price: 16.99,
    songKey: "G Minor",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 8,
    name: "The winner takes it all",
    artist: "ABBA",
    parts: 3,
    pages: 6,
    duration: "04:46",
    genre: GenreEnum.Rock,
    instrument: "piano/guitar",
    price: 14.99,
    songKey: "D Major / G Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 9,
    name: "Don't stop me now",
    artist: "Queen",
    parts: 2,
    pages: 3,
    duration: "05:14",
    genre: GenreEnum.Rock,
    instrument: "guitar",
    price: 25.99,
    songKey: "A Major / D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 10,
    name: "Someone like you",
    artist: "Adele",
    parts: 1,
    pages: 3,
    duration: "03:11",
    genre: GenreEnum.Popular,
    instrument: "piano",
    price: 17.99,
    songKey: "C Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 11,
    name: "Easy on me",
    artist: "Adele",
    parts: 1,
    pages: 3,
    duration: "03:34",
    genre: GenreEnum.Popular,
    instrument: "piano/guitar",
    price: 14.99,
    songKey: "C Minor",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 12,
    name: "Perfect",
    artist: "Ed Sheeran",
    parts: 1,
    pages: 3,
    duration: "02:46",
    genre: GenreEnum.Popular,
    instrument: "piano",
    price: 14.99,
    songKey: "D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 13,
    name: "Country roads",
    artist: "J.Denver",
    parts: 1,
    pages: 3,
    duration: "04:46",
    genre: GenreEnum.Country,
    instrument: "guitar",
    price: 16.99,
    songKey: "F Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 14,
    name: "Jolene",
    artist: "D.Parton",
    parts: 2,
    pages: 4,
    duration: "02:46",
    genre: GenreEnum.Country,
    instrument: "piano",
    price: 11.99,
    songKey: "F Minor / D Minor",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 15,
    name: "That's all right",
    artist: "E.Presley",
    parts: 1,
    pages: 3,
    duration: "02:51",
    genre: GenreEnum.Country,
    instrument: "piano",
    price: 16.99,
    songKey: "D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
  {
    id: 16,
    name: "Remember When",
    artist: "A.Jackson",
    parts: 1,
    pages: 3,
    duration: "02:46",
    genre: GenreEnum.Country,
    instrument: "piano/guitar",
    price: 18.99,
    songKey: "D Major",
    difficulty: DificulltyLevelEnum.Intermediate,
    description: appConstants.loremIpsumDescription,
  },
];

export default GridItemData;
